# Generated by Django 5.1.1 on 2024-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_departments_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/images/')),
            ],
        ),
    ]
