# Generated by Django 5.1.1 on 2024-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('doctor', models.CharField(max_length=255, verbose_name='Doctor')),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('preferred_time', models.TimeField(verbose_name='Preferred Time')),
                ('additional_note', models.TextField(verbose_name='Additional Note')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
        ),
    ]
